#!/bin/bash
case $1 in
  BAT1)
    _acpi=$(acpi -b | sed -n '2 p')
    if [ ! "$_acpi" ]; then
        exit
    fi
    ;;
  *)
    _acpi=$(acpi -b)
    ;;
esac

stat=$(echo $_acpi |cut -d ":" -f2 | cut -d "," -f 1 | sed -e 's/^[ \t]*//')
percent=$(echo $_acpi | sed '$!d;/%/{s/%.*//;s/.*\s//}')

case "$stat" in
  Full)
    symbol='🌩'
    ;;
  Charging)
    symbol='⚡'
    ;;
  Discharging)
    symbol=''
    ;;
esac

echo "$symbol" "$percent""%"
echo "$symbol" "$percent""%"


case $(echo "$percent"" / 20" | bc) in
  0)
    echo "#FF0000"
    ;;
  1)
    echo "#FF8400"
    ;;
  2)
    echo "#FFF700"
    ;;
  3)
    echo "#AAFF00"
    ;;
  *)
    echo "#00FF00"
    ;;
esac
