#!/bin/bash
stat=$(acpi -b |cut -d ":" -f2 | cut -d "," -f 1 | sed -e 's/^[ \t]*//')
percent=$(acpi -b | cut -d ":" -f2 | grep -o '[0-9]*')

case "$stat" in
  Full)
    symbol='🌩'
    ;;
  Charging)
    symbol='⚡'
    ;;
  Discharging)
    symbol=''
    ;;
esac

echo "$symbol" "$percent""%" 
echo "$symbol" "$percent""%"


case $(echo ""$percent" / 20" | bc) in
  0)
    echo "#FF0000"
    ;;
  1)
    echo "#FF8400"
    ;;
  2)
    echo "#FFF700"
    ;;
  3)
    echo "#AAFF00"
    ;;
  *)
    echo "#00FF00"
    ;;
esac
