#!/bin/bash
PACTL=$(pactl list sinks | grep --after-context 10 "^[[:space:]]State: RUNNING")

VOLUME=$(echo "$PACTL" | grep -Eo "[0-9]+\%" | head -n1)

MUTE_STATUS=$(echo "$PACTL" | grep "Mute" | cut -d' ' -f2)

if [[ $MUTE_STATUS = yes ]]; then
    echo "MUTE"
    echo "MUTE"
else
    echo "$VOLUME"
    echo "$VOLUME"
fi
