#!/bin/bash
PACTL=$(pactl list sinks)

VOLUME=$(echo "$PACTL" | grep "^[[:space:]]Volume" | cut -d'/' -f 2 | sed 's/ //g')

MUTE_STATUS=$(echo "$PACTL" | grep "Mute" | cut -d':' -f2 | sed "s/ //g")

if [[ $MUTE_STATUS = yes ]]; then
    echo "MUTE"
    echo "MUTE"
else
    echo "$VOLUME"
    echo "$VOLUME"
fi
