#!/bin/bash
PACTL=$(pactl list sinks | grep --after-context 10 "^[[:space:]]State: RUNNING")

VOLUME=$(echo "$PACTL" | grep "^[[:space:]]Volume" | cut -d' ' -f5)

MUTE_STATUS=$(echo "$PACTL" | grep "Mute" | cut -d' ' -f2)

if [[ $MUTE_STATUS = yes ]]; then
    echo "MUTE"
    echo "MUTE"
else
    echo "$VOLUME"
    echo "$VOLUME"
fi
