#!/bin/bash
export DOTFILES=$(pwd)

###### Install standard workflow #####
source .workflow
#packages
yes | sudo pacman -S  "${packages[@]}"

source $DOTFILES/zsh/alias/aura.zsh

#aur packages
for p in "${aurpackages[@]}"
do
    aura "$p"
done

#npm packages
for p in "${npmpackages[@]}"
do
    sudo npm install "$p" -g
done

sh storeTools
sh nail
