#!/bin/bash
# Deploy dotfiles and install programs that are part of my [workflow](.workflow)
set -e

source .workflow

_global_dark_theme(){
    echo -e "\033[32mInstalling global dark theme...\033[0m"
    wget -P /tmp "https://github.com/Mrcuve0/Aritim-Dark/archive/master.zip"
    unzip -q /tmp/master.zip -d /tmp
    mkdir -p "$HOME"/.themes
    mv /tmp/Aritim-Dark-master/GTK "$HOME"/.themes/ayu
    rm -r /tmp/{Aritim-Dark-master,master.zip}
}

_make_repos(){
    for repo in "$@"; do
        name="$(basename "$repo")"
        echo -e "\033[32mInstalling $name...\033[0m"
        git clone "$repo" /tmp/"$name"
        sudo make install -C /tmp/"$name"
        rm -rf /tmp/"$name"
    done
}

read -r -p "Type of installation [(F)ULL | (h)eadless]: "
case "$REPLY" in
    FULL|F|"")
        type="full"
        ;;
    headless|h)
        type="headless"
        ;;
    *)
        echo "Invalid type of installation"
        exit
        ;;
esac

case "$type" in
    full)
        sudo pacman -Suyy --needed  "${all_pacman[@]}"
        bash nail
        _make_repos "${all_repos[@]}"
        aura -S "${all_aur[@]}"
        _global_dark_theme
        ;;
    headless)
        sudo pacman -Suyy --needed  "${essential_pacman[@]}"
        bash nail --headless
        _make_repos "${essential_repos[@]}"
        aura -S "${essential_aur[@]}"
        ;;
esac

mkdir -vp "$HOME/dl"
mkdir -vp "$HOME/docs"
mkdir -vp "$HOME/media/pics"
mkdir -vp "$HOME/media/videos"
mkdir -vp "$HOME/repos"
