#!/bin/bash
set -e
export DOTFILES=$(pwd)

###### Install standard workflow #####
sh storeTools

source .workflow
#packages
yes | sudo pacman -S --needed  "${packages[@]}"

#aur packages
for p in "${aurpackages[@]}"
do
    aura -S "$p"
done

sh nail
