#!/bin/bash
# autogenerate [README](README.md)

generate_description(){
    find "$1" -maxdepth 1 -type f -not -path '*/\.*' |
        sort |
        while read -r script; do
            [ "$(sed -n '/^#!/p;q' "$script")" ] || continue
            filename="$(basename -- "$script")"
            echo -n "* [${filename%.*}]($script) "
            sed -n 2p "$script" | sed 's/ *# *//g;s/ *""" *//g'
        done
}

echo \
"# Toolbelt
Collection of scripts and dotfiles that follow me on all of my linux adventures

## :hammer: [Powertools](powertools) (.dotfiles)
Static config files

## 🧰 [Toolbox](toolbox)(scripts)
Scripts used in the terminal or on a keybind
$(generate_description "toolbox")

## :wrench: [Toolkit](toolkit) (dmenu scripts)
Scripts launched from my [menu](toolbox/menu.tool)
$(generate_description "toolkit")

## :iphone: [Handtools](handtools)
Scripts I use on my phone (used with [Tasker](https://tasker.joaoapps.com/) and
[Termux](https://github.com/termux/termux-app))
$(generate_description "handtools")

## :link: Install
Collection of installation scripts
$(generate_description .)

## License
This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details"
