#!/bin/bash
# autogenerate [README](README.md)

generate_description(){
    find "$1" -maxdepth 1 -type f -not -path '*/\.*' |
        sort |
        while read -r script; do
            [ "$(sed -n '/^#!/p;q' "$script")" ] || continue
            filename="$(basename -- "$script")"
            echo -n "* [${filename%.*}]($script) "
            sed -n 2p "$script" | sed 's/ *# *//g;s/ *""" *//g'
        done
}

generate_blueprints(){
    find "./blueprints" -maxdepth 1 -type f -not -name README.md |
        sort |
        while read -r script; do
            file="$(basename "$script")"
            title="$(head -n 1 "$script" | sed 's/ *# *//g')"
            echo "* [$title]($file)"
        done
}


echo \
"# :blue_book: Blueprints

Notes I take on my linux ~~tribulations~~ adventures in case I ever need to repeat them

## Index
$(generate_blueprints)" >| blueprints/README.md
git add blueprints/README.md

echo \
"# Toolbelt
Collection of scripts, dotfiles and self-created guides that follow me on all
of my linux adventures

## :hammer: [Powertools](powertools) (.dotfiles)
Static config files

## 🧰 [Toolbox](toolbox)(scripts)
Scripts used in the terminal or on a keybind
$(generate_description "toolbox")

## :wrench: [Toolkit](powertools/dmenu/scripts) (dmenu scripts)
Scripts launched from my [menu](toolbox/menu.tool)
$(generate_description "powertools/dmenu/scripts")

## :iphone: [Handtools](handtools)
Scripts I use on my phone (used with [Tasker](https://tasker.joaoapps.com/) and
[Termux](https://github.com/termux/termux-app))
$(generate_description "handtools")


## :link: Install
Installation scripts I use to setup my dotfiles
$(generate_description .)

## :blue_book: [Blueprints](blueprints)
Notes I take on my linux ~~tribulations~~ adventures in case I ever need to repeat them

## License
This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details" >| README.md
git add README.md
