#!/bin/bash
# autogenerate [README](README.md)

generate_description(){
    find "$1" -maxdepth 1 -type f -not -path '*/\.*' |
        sort |
        while read -r script; do
            [ "$(sed -n '/^#!/p;q' "$script")" ] || continue
            filename="$(basename -- "$script")"
            echo -n "* [${filename%.*}]($script) "
            sed -n 2p "$script" | sed 's/ *# *//g'
        done
}

toolbox(){
    echo "## 🧰 [Toolbox](toolbox)(scripts)"
    echo
    echo "Colection of scripts to be used in the terminal or a keybind"
    echo
    generate_description "toolbox"
}

toolkit(){
    echo "## :wrench: [Toolkit](toolkit) (dmenu scripts)"
    echo
    echo "Collection of scripts to be launched from a [menu](toolbox/menu.tool)"
    echo
    generate_description "toolkit"
}

powertools(){
    echo "## :hammer: [Powertools](powertools) (.dotfiles)"
    echo
    echo "Colection of static config files"
}

install(){
    echo "## :link: Install"
    echo
    echo "Collection of installation scripts"
    echo
    generate_description .
}

echo "# Toolbelt"
echo
echo "Collection of scripts and dotfiles that follow me in all of my linux adventures"
echo

for section in toolbox toolkit powertools install; do
    $section
    echo
done

echo "## License"
echo
echo "This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details"
