#!/bin/bash
# run job scheduler for [Termux](https://github.com/termux/termux-app)

[[ "$DOTFILES" ]] || DOTFILES="$(dirname "$(readlink -f "$0")")"

_termux_task_set(){
    echo -e "\033[35mSetting task:\033[33m $1 (every: $2 ms)\033[0m"
    termux-job-scheduler \
        --script "$DOTFILES/handtools/$1.tool" \
        --period-ms "$2" \
        --persisted true
}

! command -V termux-job-scheduler &> /dev/null &&
    echo "Not in termux env" && exit

termux-job-scheduler --cancel-all
_termux_task_set change_lock 900000
