runtime! archlinux.vim

if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

Plug 'morhetz/gruvbox'

Plug 'PotatoesMaster/i3-vim-syntax'

Plug 'scrooloose/nerdtree'

Plug 'Xuyuanp/nerdtree-git-plugin'

Plug 'kien/ctrlp.vim'

Plug 'tpope/vim-commentary'

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

Plug 'deoplete-plugins/deoplete-jedi'

Plug 'zchee/deoplete-clang'

Plug 'deoplete-plugins/deoplete-jedi'

Plug 'junegunn/goyo.vim'

" Let me sudo save in nvim
Plug 'lambdalisue/suda.vim'

call plug#end()

""" PLUGIN CONFIGS

" Gruvbox config
colorscheme gruvbox
set background=dark
let g:gruvbox_contrast_dark = 'hard'
highlight Normal ctermbg=None

" Nerdtree config
map <F2> :NERDTreeToggle<CR>

" let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1

" hide brackets around git status
augroup nerdtreeconcealbrackets
      autocmd!
      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\]" contained conceal containedin=ALL
      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\[" contained conceal containedin=ALL
      autocmd FileType nerdtree setlocal conceallevel=2
      autocmd FileType nerdtree setlocal concealcursor=nvic
augroup END

" custom simbols for git status
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "! ",
    \ "Staged"    : "+ ",
    \ "Untracked" : "? ",
    \ "Renamed"   : "> ",
    \ "Unmerged"  : "# ",
    \ "Deleted"   : "- ",
    \ "Dirty"     : "? ",
    \ "Clean"     : "",
    \ "Ignored"   : "",
    \ "Unknown"   : ""
    \ }

" quit nerdtree on open
let NERDTreeQuitOnOpen = 1

" deoplete.
let g:deoplete#enable_at_startup = 1
inoremap <silent><expr> <TAB>
            \ pumvisible() ? "\<C-n>" :
            \ <SID>check_back_space() ? "\<TAB>" :
            \ deoplete#manual_complete()
function! s:check_back_space() abort "{{{
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~ '\s'
endfunction"}}}

" deoplete
let g:deoplete#sources#clang#libclang_path = '/usr/lib/libclang.so'
let g:deoplete#sources#clang#clang_header = '/usr/include/'

" CtrlP
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_custom_ignore = '\v[\/](\.git|\.hg|\.env|\.svn|node_modules|target|out)$'


" LaTeX
autocmd BufEnter *.tex set linebreak
autocmd FileType tex map <Space>r :silent !pdflatex --shell-escape %:p <enter>
autocmd BufEnter *.tex command! Re !pdflatex --shell-escape %:p

"lp_solve
autocmd BufEnter *.lp map <Space>r :!lp_solve %:p <enter>
autocmd BufEnter *.lp set syntax=perl

""" SETTINGS
" indent using spaces
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

" show line number
set number

" copy paste in vim
inoremap <C-v> <ESC>"+pa
vnoremap <C-c> "+y
vnoremap <C-x> "+d

" split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

nnoremap <M-h> <C-w>H
nnoremap <M-j> <C-w>J
nnoremap <M-k> <C-w>K
nnoremap <M-l> <C-w>L

" Ctrl+S to save
map <C-S> :w<CR>
imap <C-S> <Esc>:w<CR>a

" Alt-Tab
map <Space><Tab> :e #<CR>

" Scroll with mouse
set mouse=a

" clear search register
nmap <space><space> :noh<CR>

"spelling
set spell! spelllang=en_gb,pt_pt
" Open spelling suggestions
nnoremap <A-Enter> z=

""" COMMANDS
command! W w
command! Q q
command! WQ wq

set undodir=~/.cache/vimundo
set undofile

set scrolloff=4
