#!/bin/bash

case "$1" in
    magnet:?*)
            if python ~/.local/bin/qbt -a "$1"; then
                termux-toast "queued torrent" & disown
            else
                termux-toast "failed to queue torrent" & disown
            fi
            ;;

    *)
        termux-toast "error: no case implemented" & disown
        ;;
esac

exit
