#!/bin/python
from i3ipc import Connection, Event
import sys

i3 = Connection()

def print_workspaces():
    print('%{F-}', end='')
    for workspace in i3.get_workspaces():
        name = workspace.name

        if workspace.urgent:
            print('%{B#E6900000} ', name, end='')
        elif workspace.focused:
            print('%{B#E6285577} ', name, end='')
        else:
            print('%{B#E6222222} ', name, end='')

        print('  %{B-} ', end='')
    print()

    sys.stdout.flush()

def react_on_event(self, e):
    print_workspaces()

i3.on(Event.WORKSPACE_FOCUS, react_on_event)
i3.on(Event.WORKSPACE_URGENT, react_on_event)
i3.on(Event.WINDOW_MOVE, react_on_event)
i3.on(Event.WINDOW_NEW, react_on_event)
i3.on(Event.WINDOW_URGENT, react_on_event)

print_workspaces()

i3.main()
