#!/bin/bash
[[ $- != *i* ]] && return # Do nothing if not running interactively

stty -ixon # Disable ctrl-s and ctrl-q

BASH_FILES=~/.toolbelt/powertools/bash

# History settings
export HISTSIZE=""
PROMPT_COMMAND='history -a;history -n'
export HISTCONTROL='ignoredups'
shopt -s histappend
shopt -s histverify
shopt -s checkwinsize
set -o noclobber

GPG_TTY="$(tty)"; export GPG_TTY

# Source all global configs
#shellcheck disable=SC1090
for f in "$BASH_FILES"/*.bash; do . "$f"; done

# Source local configs
local="$BASH_FILES"/"$(hostname)".local
#shellcheck disable=SC1090
[ -f "$local" ] && . "$local"
