#!/bin/bash
[[ $- != *i* ]] && return

[[ ! "$DOTFILES" ]] && \
    export DOTFILES="$(dirname "$(dirname "$(dirname "$(readlink ".bash_profile")")")")"

export HISTSIZE=""
PROMPT_COMMAND='history -a;history -n'
export HISTCONTROL='ignoredups'
shopt -s histappend
shopt -s histverify
shopt -s checkwinsize
set -o noclobber

bind "set completion-ignore-case On"
bind "set show-all-if-unmodified on"

GPG_TTY="$(tty)"
export GPG_TTY

for f in "$DOTFILES/powertools/bash/"*.bash; do
    #shellcheck disable=SC1090
    source "$f"
done
