#!/bin/bash
export PATH=$HOME/.local/bin:$PATH

# Default programs
export TERMINAL="alacritty"
export BROWSER="firefox"
export VISUAL="nvim"
export EDITOR="nvim"

# Global configs
export PAGER="less -isg"
export LESS_TERMCAP_mb=$'\e[1;35m'
export LESS_TERMCAP_md=$'\e[1;36m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;32m'

export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
export JQ_COLORS='1;31:0;33:0;33:0;39:0;32:1;39:1;39'

# ~/ clean-up
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# shellcheck disable=SC1090,SC1091
. "$HOME"/.config/user-dirs.dirs

mkdir -p "$XDG_CACHE_HOME/less"
export LESSKEY="$XDG_CONFIG_HOME/less/lesskey"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"

export CABAL_CONFIG="$XDG_CONFIG_HOME/cabal/config"
export CABAL_DIR="$XDG_CACHE_HOME/cabal"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export GOPATH="$XDG_DATA_HOME/go"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export IPYTHONDIR="$XDG_CONFIG_HOME/jupyter"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME/docker-machine"
export MYSQL_HISTFILE="$XDG_DATA_HOME/mysql_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export STACK_ROOT="$XDG_DATA_HOME/stack"
export VAGRANT_ALIAS_FILE="$XDG_DATA_HOME/vagrant/aliases"
export VAGRANT_HOME="$XDG_DATA_HOME/vagrant"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

# ssh
export SSH_KEY_PATH="$HOME/.ssh/rsa_id"

# shellcheck disable=SC1090,SC1091
[[ -f "$HOME/.bashrc" ]] && . "$HOME/.bashrc"

if [ "$(tty)" = "/dev/tty1" ]; then
    fetch --logo
    rm -rf /tmp/startx.log
    startx &> /tmp/startx.log
    clear
elif [[ "$SSH_CLIENT" ]]; then
    export TERM=xterm
    if hash tmux &> /dev/null && [[ ! "$TMUX" ]] && [[ "$(pwd)" = "$HOME" ]]; then
        echo -n 'Launch tmux? [y/N]'
        read -r
        case $REPLY in
            "y"|"Y")
                tmux -2 a &>/dev/null || tmux -2
                exit
                ;;
        esac
        unset REPLY
    fi
fi
