#!/bin/bash

readarray -t acpi < <(acpi -b | grep -v "rate information unavailable")
[ ${#acpi[@]} -eq 0 ] && exit

readarray -t charges < <(printf "%s\n" "${acpi[@]}" | cut -d',' -f2 | sed -E 's/[ %]//g')

max_charge="$(printf "%s\n" "${charges[@]}" | sort -nr | head -n1)"

for i in "${!charges[@]}"; do
    case "${acpi[i]}" in
        *Full*)        symbol=''  ;;
        *Charging*)    symbol='^' ;;
        *Discharging*) symbol='' ;;
    esac
    charges["$i"]="$symbol${charges[i]}%"
done

printf "%s" "${charges[0]}"

[[ "${#charges[@]}" -gt 1 ]] &&
    printf "    %s" "${charges[@]:1}"

echo ""

case "$(( max_charge / 20 ))" in
  0) echo "#FF0000" ;;
  1) echo "#FF8400" ;;
  2) echo "#FFF700" ;;
  3) echo "#AAFF00" ;;
  *) echo "#00FF00" ;;
esac
