#!/bin/bash
_acpi="$(acpi -b | grep -v "rate information unavailable")"

[ -n "$1" ] && \
    _acpi="$(echo "$_acpi" | sed -n "$(($1 + 1))p")"

[ ! "$_acpi" ] && exit

stat=$( \
    echo "$_acpi" | \
    cut -d ":" -f2 | \
    cut -d "," -f 1 | \
    sed -e 's/^[ \t]*//')

percent=$(echo "$_acpi" | sed '$!d;/%/{s/%.*//;s/.*\s//}')

case "$stat" in
  Full)        symbol=''  ;;
  Charging)    symbol='^' ;;
  Discharging) symbol=''  ;;
esac

echo "$symbol" "$percent""%"

case "$(( percent / 20 ))" in
  0) echo "#FF0000" ;;
  1) echo "#FF8400" ;;
  2) echo "#FFF700" ;;
  3) echo "#AAFF00" ;;
  *) echo "#00FF00" ;;
esac
