#!/bin/bash

grep_field(){
    echo "$ecard_stats" | grep "$1" | cut -d: -f2 | xargs
}

print_block(){
    ecard_stats="$(nmcli device show |
        grep ethernet \
            --before-context 1 \
            --after-context 10 \
            -m 1)"

    if echo "$ecard_stats" | grep -q "(connected)"; then
        name="$(grep_field "GENERAL.CONNECTION")"
        device="$(grep_field "GENERAL.DEVICE")"

        speed="$(cat "/sys/class/net/${device}/speed" )"

        [ "$speed" -lt "0" ] && echo && return

        unit="Mbps"
        if [ "$speed" -ge "1000" ]; then
            if (( speed % 1000 == 0 )); then
                speed="$(( speed / 1000 ))"
            else
                speed="$(printf %.1f "$(( speed/1000 ))e-3" )"
            fi

            unit="Gbps"
        fi

        color="#FF0000"
        if [ "$speed" -ge "10000" ]; then
            color="#00FF00"
        elif [ "$speed" -ge "5000" ]; then
            color="#AAFF00"
        elif [ "$speed" -ge "2500" ]; then
            color="#FFF700"
        elif [ "$speed" -ge "1000" ]; then
            color="#FF8400"
        fi

        echo "%{F$color}${speed}${unit}@${name}%{F-}"
    else
        echo
    fi
}

print_block
while read -r; do
    print_block
done <  <(nmcli monitor | grep -E --line-buffered "(connected|disconnected|device removed)$")
