#!/bin/bash

print_block(){
    readarray -t connections < <(nmcli --terse connection show --active)

    [[ "${#connections[@]}" -eq 0 ]] && echo && return

    main_connection="${connections[0]}"
    for connection in "${connections[@]}"; do
        type="$(echo "$connection" | cut -d':' -f3)"
        case "$type" in
            *ethernet*)
                main_connection="$connection"
                ;;
        esac
    done

    name="$(echo "$main_connection" | cut -d':' -f1)"
    type="$(echo "$main_connection" | cut -d':' -f3)"
    device="$(echo "$main_connection" | cut -d':' -f4)"

    case "$type" in
        *ethernet*)
            speed="$(cat "/sys/class/net/${device}/speed" )"

            [ "$speed" -lt "0" ] && echo && return

            color="$(range2color --max 10000 "$speed")"

            unit="Mbps"
            if [ "$speed" -ge "1000" ]; then
                if (( speed % 1000 == 0 )); then
                    speed="$(( speed / 1000 ))"
                else
                    speed="$(printf %.1f "$(( speed/1000 ))e-3" )"
                fi

                unit="Gbps"
            fi


            echo "%{F$color}${speed}${unit}@${name}%{F-}"
            ;;

        *wireless*)
            if _iwconfig="$( iwconfig "${device}" 2>/dev/null )"; then

                cur="$(echo "${_iwconfig}" | \
                    grep -oE 'Link Quality=[/0-9]+' | \
                    grep -oE '[0-9]+' | \
                    head -1)"
                max="$(echo "${_iwconfig}" | \
                    grep -oE 'Link Quality=[/0-9]+' | \
                    grep -oE '[0-9]+' | \
                    tail -1)"

                color="$(range2color --max "$max" "$cur")"

                echo "%{F${color}}${name}%{F-}"
            else
                echo
            fi
            ;;
        *)
            echo
            ;;
    esac
}

print_block
nmcli monitor | grep -E --line-buffered "(connected|disconnected|device removed)$" | while read -r; do
    print_block
done
