#!/bin/bash
iface="$( \
    tail -1 /proc/net/wireless 2>/dev/null | \
    awk '{print $1}' | \
    sed 's/://g' )"

if _iwconfig="$( iwconfig "${iface}" 2>/dev/null )"; then
    ssid=$(iwgetid -r 2>/dev/null)

    quality="$(awk \
        -v cur="$( \
            echo "${_iwconfig}" | \
            grep -oE 'Link Quality=[/0-9]+' | \
            grep -oE '[0-9]+' | \
            head -1)" \
        -v max="$( \
            echo "${_iwconfig}" | \
            grep -oE 'Link Quality=[/0-9]+' | \
            grep -oE '[0-9]+' | \
            tail -1)" \
        'BEGIN{printf("%0.f", cur*100/max)}')"

    echo "$quality%@$ssid"

    case $(echo "$quality"" / 20" | bc) in
        0) echo "#FF0000" ;;

        1) echo "#FF8400" ;;

        2) echo "#FFF700" ;;

        3) echo "#AAFF00" ;;

        *) echo "#00FF00" ;;
    esac
fi

