#!/bin/bash

print_block(){
    iface="$( \
        tail -1 /proc/net/wireless 2>/dev/null | \
        awk '{print $1}' | \
        sed 's/://g' )"

    if _iwconfig="$( iwconfig "${iface}" 2>/dev/null )"; then
        ssid=$(iwgetid -r 2>/dev/null)

        quality="$(awk \
            -v cur="$( \
                echo "${_iwconfig}" | \
                grep -oE 'Link Quality=[/0-9]+' | \
                grep -oE '[0-9]+' | \
                head -1)" \
            -v max="$( \
                echo "${_iwconfig}" | \
                grep -oE 'Link Quality=[/0-9]+' | \
                grep -oE '[0-9]+' | \
                tail -1)" \
            'BEGIN{printf("%0.f", cur*100/max)}')"

        color="#00FF00"
        case "$(( quality / 20 ))" in
            0) color="#FF0000" ;;
            1) color="#FF8400" ;;
            2) color="#FFF700" ;;
            3) color="#AAFF00" ;;
        esac
        echo "%{F$color}$quality%@$ssid%{F-}"
    else
        echo
    fi
}

print_block
while read -r; do
    print_block
done <  <(nmcli monitor | grep -E --line-buffered "(connected|disconnected)$")
