#!/bin/python
"""block to display i3 workspaces on thonkbar"""
from sys import stdout

from i3ipc import Connection, Event # type: ignore

I3WM = Connection()

def print_workspaces():
    """print workspaces in lemonbar format"""
    print('%{F-}', end='')
    for workspace in I3WM.get_workspaces():
        name = workspace.name

        if workspace.urgent:
            print('%{B#E6900000} ', name, end='')
        elif workspace.focused:
            print('%{B#E6285577} ', name, end='')
        else:
            print('%{B#E6222222} ', name, end='')

        print('  %{B-} ', end='')
    print()

    stdout.flush()

def react_on_event(_, __):
    """function to handle events"""
    print_workspaces()

I3WM.on(Event.WORKSPACE_FOCUS, react_on_event)
I3WM.on(Event.WORKSPACE_URGENT, react_on_event)
I3WM.on(Event.WINDOW_MOVE, react_on_event)
I3WM.on(Event.WINDOW_NEW, react_on_event)
I3WM.on(Event.WINDOW_URGENT, react_on_event)

print_workspaces()

I3WM.main()
