#!/bin/python
"""block to display i3 workspaces on thonkbar"""
from os import name
from sys import stdout

from i3ipc import Connection, Event # type: ignore

I3WM = Connection()

def print_workspaces():
    """print workspaces in lemonbar format"""

    workspaces = [None] * 10

    for workspace in I3WM.get_workspaces():
        try:
            name_int = (int(workspace.name)) - 1
            if workspace.urgent:
                workspaces[name_int] = '%{F#E6f22c40}'
            elif workspace.focused:
                workspaces[name_int] = '%{F#E6407ee7}'
            else:
                workspaces[name_int] = '%{F#E6a8a19f}'
        except ValueError:
            print("re")

    while workspaces[-1] is None:
        workspaces.pop()

    workspaces = [x if x else "%{F#E6a8a18f}" for x in workspaces]

    print(*workspaces, "%{F-}")
    stdout.flush()

def react_on_event(_, __):
    """function to handle events"""
    print_workspaces()

I3WM.on(Event.WORKSPACE_FOCUS, react_on_event)
I3WM.on(Event.WORKSPACE_URGENT, react_on_event)
I3WM.on(Event.WINDOW_MOVE, react_on_event)
I3WM.on(Event.WINDOW_NEW, react_on_event)
I3WM.on(Event.WINDOW_URGENT, react_on_event)

print_workspaces()

I3WM.main()
