setxkbmap -layout gb -option caps:escape
numlockx on

compton --config $DOTFILES/powertools/compton/compton.conf -b
dunst &
nm-applet &
changeWall &
sxhkd &

case $(hostname) in
    cake)
        exec bspwm
        ;;
    *)
        exec i3
        ;;
esac
