xrdb -merge ~/.config/X11/Xresources

case $(hostname) in
    cake) ;;
    *) picom --experimental-backends --daemon ;;
esac

dunst &
unclutter --timeout 1 --jitter 10 --ignore-scrolling --fork
wall &
sxhkd &
thonkbar &

exec i3
