name: Shellcheck CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install shellcheck
      run: sudo apt-get install -y shellcheck
    - name: Run shellcheck
      run: |
        readarray -t files < <(grep -rIzlE '^#![[:blank:]]*/bin/(bash|sh)' .)
        shellcheck "${files[@]}"
